"""initial migration

Revision ID: 2c3c9559cb53
Revises: 
Create Date: 2025-12-18 12:21:38.201651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c3c9559cb53'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizer_wallets_id'), table_name='organizer_wallets')
    op.drop_table('organizer_wallets')
    op.drop_index(op.f('ix_match_availability_club_id'), table_name='match_availability')
    op.drop_index(op.f('ix_match_availability_id'), table_name='match_availability')
    op.drop_index(op.f('ix_match_availability_match_id'), table_name='match_availability')
    op.drop_table('match_availability')
    op.drop_column('playing_xi', 'updated_at')
    op.drop_index(op.f('ix_tournament_payments_transaction_id'), table_name='tournament_payments')
    op.create_index(op.f('ix_tournament_payments_transaction_id'), 'tournament_payments', ['transaction_id'], unique=True)
    # op.add_column('tournaments', sa.Column('is_blocked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###
    op.add_column(
    'tournaments',
    sa.Column(
        'is_blocked',
        sa.Boolean(),
        nullable=False,
        server_default=sa.false()
    )
)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'is_blocked')
    op.drop_index(op.f('ix_tournament_payments_transaction_id'), table_name='tournament_payments')
    op.create_index(op.f('ix_tournament_payments_transaction_id'), 'tournament_payments', ['transaction_id'], unique=False)
    op.add_column('playing_xi', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_table('match_availability',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('club_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_available', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('confirmed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_match_availability_club'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_match_availability_match'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('match_availability_pkey')),
    sa.UniqueConstraint('match_id', 'club_id', name=op.f('uq_match_availability_match_club'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_match_availability_match_id'), 'match_availability', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_availability_id'), 'match_availability', ['id'], unique=False)
    op.create_index(op.f('ix_match_availability_club_id'), 'match_availability', ['club_id'], unique=False)
    op.create_table('organizer_wallets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organizer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('balance', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], name=op.f('organizer_wallets_organizer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('organizer_wallets_pkey')),
    sa.UniqueConstraint('organizer_id', name=op.f('organizer_wallets_organizer_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_organizer_wallets_id'), 'organizer_wallets', ['id'], unique=False)
    # ### end Alembic commands ###
