"""name changed to club_name clubs table columns

Revision ID: 67d0873993a0
Revises: 4bb214ccc337
Create Date: 2025-11-15 20:15:39.664275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67d0873993a0'
down_revision: Union[str, Sequence[str], None] = '4bb214ccc337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('club_name', sa.String(), nullable=False))
    op.drop_constraint(op.f('clubs_name_key'), 'clubs', type_='unique')
    op.create_unique_constraint(None, 'clubs', ['club_name'])
    op.drop_column('clubs', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'clubs', type_='unique')
    op.create_unique_constraint(op.f('clubs_name_key'), 'clubs', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('clubs', 'club_name')
    # ### end Alembic commands ###
