"""Add chat messages table

Revision ID: 8feb4026cabb
Revises: add_tournament_type
Create Date: 2025-12-25 15:58:25.528824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8feb4026cabb'
down_revision: Union[str, Sequence[str], None] = 'add_tournament_type'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'tournament_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('tournament_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
