"""add prize amount

Revision ID: add_prize
Revises: add_tournament_winner
Create Date: 2026-02-17 22:20:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_prize'
down_revision = 'add_tournament_winner'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_details', sa.Column('prize_amount', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0.00'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament_details', 'prize_amount')
    # ### end Alembic commands ###
