"""Add club_image column to clubs table

Revision ID: d688b0ad12dd
Revises: ab0d22e79f34
Create Date: 2025-11-22 19:54:18.467216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd688b0ad12dd'
down_revision: Union[str, Sequence[str], None] = 'ab0d22e79f34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('club_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'club_image')
    # ### end Alembic commands ###
