"""add_organization_image_column

Revision ID: e8e2aa8e30a6
Revises: bba14a6b2d6d
Create Date: 2025-11-22 07:09:41.617956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8e2aa8e30a6'
down_revision: Union[str, Sequence[str], None] = 'bba14a6b2d6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_details', sa.Column('organization_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_details', 'organization_image')
    # ### end Alembic commands ###
